Remove pin to `Django==5.1` causing dependency error
Error:
ERROR: Cannot install Django==5.1 and edc==0.6.15 because these
package versions have conflicting dependencies.

Fix:
Use Django dependency specified in edc 0.6.15 (`Django>=5.1.2`)